spring:

  # Service name in Eureka
  application:
    name: service-discovery

# Eureka Server
eureka:
  instance:
    hostname: localhost
  server:
    renewalPercentThreshold: 0.33
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

# Tomcat port
server:
  port: 9999