# Eureka Server
eureka:
  server:
    renewalPercentThreshold: 0.33
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

# Tomcat port
server:
  port: 9999